name: dev-tools-portainer

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-2.45.2}
    restart: "no"
    ports:
      - "127.0.0.1:${PORTAINER_PORT:-9443}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  portainer-data:
